### ISSUE TITLE
offline with a 404

### ISSUE THREAD

**Issue by harry-wood** [osmlab/osm-note#15]
This is offline with a 404 now: http://osmlab.github.io/mobile-note/

**Comment by iandees** [comment]
The URL is http://osmlab.github.io/osm-note/. Where did you find that URL?

**Comment by harry-wood** [comment]
Aha! That works even better with httpS  (for geolocation)

Found the wrong URL in the README

**Comment by iandees** [comment]
Fixed in 16295c2.

**Comment by harry-wood** [comment]
Nice one.
And the website URL in the github repo settings should be httpS not http too.

**Comment by iandees** [comment]
> the website URL in the github repo settings should be httpS not http too

Updated that, too. Thanks!
