### ISSUE TITLE
show existing notes

### ISSUE THREAD

**Issue by mikelmaron** [osmlab/osm-note#3]

**Comment by tmcw** [comment]
Fixed in 29236d2cfe15f1f2eab8129ed9b8bd84d9b82a7d needs tweaking.

**Comment by mikelmaron** [comment]
no more zoom in/out buttons?

**Comment by tmcw** [comment]
Afaik, all modern mobile devices support pinch-zooming?

**Comment by mikelmaron** [comment]
yes duh. was testing on a laptop here. nevermind!
