### ISSUE TITLE
ZoomOutIn control

### ISSUE THREAD

**Issue by posikifi** [osmlab/osm-note#7]
Hi,

Is it possible to get ZoomOutIn controls in UI I have problems to use this mobile app in my Android phone.

P

**Comment by tmcw** [comment]
Can you pinch-zoom at all? What Android phone are you using? I'll probably add zoom controls, but was under the impression that Leaflet would support pinch-zooming on most devices.

**Comment by posikifi** [comment]
I have only test Galaxy SII, Android 2.3.3. Pinch zoom doesn't work at all in your app. I made leaflet map few months ago and I think I hadn't any problems with pinch-zoom. I need to check application tomorrow.

P

**Comment by posikifi** [comment]
Ok, I just read Leaflet documentation:" Pinch-Zoom on Android 4: In the previous Leaflet version, pinch-zoom only worked on iOS devices, but now it finally comes to Android! Works for Android 4+ not only in the stock browser, but also on Chrome and Firefox for Android." So, maybe you can just add zoom in-out controls for us who don't have most modern devices.

**Comment by tmcw** [comment]
Zoom controls are now added when pinch zoom is not available
